dirSources = ['os.cpp', 'micro.cpp', 'mono.cpp', 
              'monoAppFactory.cpp', 'monoApplication.cpp',
              'microApplication.cpp', 'microAppFactory.cpp',
              'request.cpp']

Export('dirSources')
