Import('env')

targetName = 'osSim'
srcs = ['main.cpp', 'os.cpp', 'monoOS.cpp', 'config.cpp',
        'environment.cpp', 'core.cpp', 'application.cpp',
        'appQueue.cpp', 'syscall.cpp', ]

t = env.Program(target = targetName, source = srcs)
Default(t)
